version: '3.8'

services:
  db:
    image: postgres:16-alpine3.21

    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: "oe1_db"
      POSTGRES_USER: "oe1_ur"
      POSTGRES_PASSWORD: "oe1_pd"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: