apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: onboarding-exercise-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: onboarding.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: clusterip-onboarding-app
                port:
                  number: 8080