<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>com.netcompany</groupId>
    <artifactId>all-apps</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <relativePath/>
  </parent>

  <artifactId>onboarding-excercise-1</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <packaging>pom</packaging>
  <modules>
    <module>onboarding-excercise-1-core</module>
    <module>onboarding-excercise-1-adapter</module>
    <module>onboarding-excercise-1-app</module>
    <module>onboarding-excercise-1-db-migration</module>
    <module>onboarding-exercise-1-rest-api</module>
    <module>onboarding-excercise-1-event</module>
  </modules>

  <properties>
    <jib-image.name>khoimdev/onboarding-exercise-1-app</jib-image.name>
  </properties>



  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>com.netcompany</groupId>
        <artifactId>onboarding-excercise-1-shared</artifactId>
        <version>${project.version}</version>
      </dependency>
    </dependencies>
  </dependencyManagement>


</project>
