--liquibase formatted sql

--changeset khoi:create-person-table
--comment: create schema PERSON
--rollback DROP TABLE IF EXISTS oe1_db.PERSON;
CREATE TABLE oe1_db.PERSON (
    PERSON_ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    FIRST_NAME VARCHAR(100) NOT NULL,
    LAST_NAME VARCHAR(100) NOT NULL,
    DATE_OF_BIRTH_DT DATE NOT NULL,
    TAX_NUMBER VARCHAR(32) UNIQUE NOT NULL,
    CREATED_DTTM TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);


