spring.application.name=onboarding-excercise-1
app.debug.stacktrace=${APP_DEBUG_STACKTRACE}

server.port=${SERVER_PORT}
server.servlet.context-path=${SERVER_SERVLET_CONTEXT_PATH}
logging.file.name=${LOGGING_FILE_NAME}

spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.datasource.hikari.maximum-pool-size=${SPRING_DATASOURCE_MAXIMUM_POOL_SIZE}
spring.datasource.hikari.minimum-idle=${SPRING_DATASOURCE_MINIMUM_IDLE}
spring.datasource.hikari.idle-timeout=${SPRING_DATASOURCE_IDLE_TIMEOUT}
spring.datasource.hikari.max-lifetime=${SPRING_DATASOURCE_MAX_LIFETIME}
spring.datasource.hikari.connection-timeout=${SPRING_DATASOURCE_CONNECTION_TIMEOUT}

spring.jpa.properties.hibernate.dialect=${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT}
spring.jpa.properties.hibernate.format_sql=${SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL}

spring.kafka.producer.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS}
spring.kafka.producer.key-serializer=${SPRING_KAFKA_PRODUCER_KEY_SERIALIZER}
spring.kafka.producer.value-serializer=${SPRING_KAFKA_PRODUCER_VALUE_SERIALIZER}

spring.kafka.admin.properties.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS}

spring.kafka.consumer.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS}
spring.kafka.consumer.key-deserializer=${SPRING_KAFKA_CONSUMER_KEY_DESERIALIZER}
spring.kafka.consumer.value-deserializer=${SPRING_KAFKA_CONSUMER_VALUE_DESERIALIZER}
spring.kafka.consumer.group-id=${SPRING_KAFKA_CONSUMER_GROUP_ID}

onboarding-exercise-1.kafka.inbound.person-topic=${ONBOARDING_PERSON_TOPIC}
onboarding-exercise-1.kafka.inbound.tax-calculation-topic=${ONBOARDING_TAX_CALC_TOPIC}
onboarding-exercise-1.kafka.inbound.test-topic=${TEST_TOPIC}

onboarding-exercise-1.kafka.manual-consumer-group-id=${MANUAL_CONSUMER_GROUP_ID}
pull.default.max=${PULL_DEFAULT_MAX}

management.endpoints.web.exposure.include=${MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE}
