spring.application.name=${SPRING_APPLICATION_NAME:onboarding-exercise-1-cron}
app.debug.stacktrace=${APP_DEBUG_STACKTRACE:true}

server.port=${SERVER_PORT:8081}
management.endpoints.web.exposure.include=${MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE:health}

onboarding-exercise-1-cron.rest.url.onboarding-exercise-1=${ONBOARDING_EXERCISE_1_CRON_REST_URL_ONBOARDING_EXERCISE_1:http://localhost:8080}
